services:
  backend:
    build: .
    container_name: backend
    init: true
    volumes:
      - ../backend:/backend
    command: sleep infinity
    networks:
      - app-network
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=123456
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/lib/mysql
    networks:
      - app-network

volumes:
  database:

networks:
  app-network:
    driver: bridge